const IMAGES = {
  background_image: require('../assets/images/bg.jpg'),
  background_lg_bg: require('../assets/images/login_bg.png'),
  background_un_bg: require('../assets/images/userName_bg.png'),
  eye_close: require('../assets/icon/eye_close.png'),
  eye_open: require('../assets/icon/eye_open.png'),
  back_arrow: require('../assets/icon/back-arrow.png'),
  back_arrow_sign: require('../assets/icon/back-arrow-sign.png'),
  down_arrow: require('../assets/icon/down-arrow.png'),
  pair_success: require('../assets/icon/pair-success.png'),
  video_bg: require('../assets/icon/video-bg.png'),
  user: require('../assets/icon/user.png'),
  motion_ai: require('../assets/icon/motion-ai.png'),
  setting: require('../assets/icon/setting.png'),
  wallet: require('../assets/icon/wallet.png'),
  walletNew: require('../assets/icon/walletNew.png'),
  wallet_bg: require('../assets/images/wallet.png'),
  clock: require('../assets/icon/clock.png'),
  watch: require('../assets/icon/watch.png'),
  settings: require('../assets/icon/settings.png'),
  terms: require('../assets/icon/terms.png'),
  contact: require('../assets/icon/contact.png'),
  policy: require('../assets/icon/policy.png'),
  notification: require('../assets/icon/notification.png'),
  invite: require('../assets/icon/invite.png'),
  profile: require('../assets/icon/profile.png'),
  star: require('../assets/icon/star.png'),
  edit: require('../assets/icon/edit.png'),
  arrow: require('../assets/icon/arrow.png'),
  toggle: require('../assets/icon/toggle.png'),
  logout: require('../assets/icon/logout.png'),
  down_arrow_black: require('../assets/icon/down-arrow-black.png'),
  person: require('../assets/icon/person.png'),
  eyeOutline: require('../assets/icon/eyeOutline.png'),
  headPhone: require('../assets/icon/headPhone.png'),
  security: require('../assets/icon/security.png'),
  about: require('../assets/icon/about.png'),
  transaction: require('../assets/icon/transaction.png'),
  profile_img: require('../assets/images/profile.png'),
  support: require('../assets/icon/support.png'),
  notification_black: require('../assets/icon/notification-black.png'),
  info_grey: require('../assets/icon/info-grey.png'),
  info_persian: require('../assets/icon/info-persian.png'),
  close_white: require('../assets/icon/close-white.png'),
  success_arrow: require('../assets/icon/success-arrow.png'),
  ckal: require('../assets/icon/ckal.png'),
  hrs: require('../assets/icon/hrs.png'),
  km: require('../assets/icon/km.png'),
  runner: require('../assets/icon/runner.png'),
  success: require('../assets/icon/success.png'),
  wallet1: require('../assets/icon/wallet1.png'),
  wallet2: require('../assets/icon/wallet2.png'),
  wallet3: require('../assets/icon/wallet3.png'),
  wallet4: require('../assets/icon/wallet4.png'),
  start_outline: require('../assets/icon/star-outline.png'),
  header_notification: require('../assets/icon/header-notification.png'),
  footsteps: require('../assets/icon/footsteps.png'),
  fire: require('../assets/icon/fire.png'),
  running: require('../assets/icon/running.png'),
  rewards: require('../assets/icon/reward.jpeg'),
};
const VIDEOS = {
  splash: require('../assets/videos/splash.mp4'),
  quick_tour: require('../assets/videos/quick-tour.mp4'),
}
const STRINGS = {
  log_in: 'Login',
  sign_up: 'Sign up',
  skip: 'Skip',
  sign_up_c: 'Sign Up',
  sign_in: 'Sign In',
  logout: 'Log Out',
  login_title: 'Let’s Sign You In.',
  login_detail: 'Welcome Back.You’ve been missed',
  sign_title: 'Create an account to connect',
  forgot_title: 'Forgot and reset your password',
  otherLoginTitle: 'Or Sign in with',
  enable_location: 'Enable Location',
  next: 'Next',
  my_state: 'My Stats',
  done: 'Done',
  submit: 'Submit',
  save: 'Save',
  ok: 'Okay',
  suggestions: 'Suggestions',

  black_friendly: 'Black Friendly Places',
  view_all: 'View All',
  waiting: 'waiting for invite',
  invite: 'Invite',
  thanks_title: 'Thanks for\nSign up',
  thanks_business__title: 'Thank you',
  landing_text:
    '"Black-Owned & Black-Friendly, Places That Treat Us With Dignity & Respect"',
  thanks_detail: 'Proceed to login with your email address and password',
  // thanks_detail:
  //   'We have sent verification email on your registered email address. Please verify your account',
  thanks_business_detail:
    'Your Black friendly business recommendation has been received',
  let_start: "Let's Start",
  no_result_detail:
    'Sorry! There are no Listings matching your search.\n\nDon’t see Black-Owned/Black-Friendly business in your area, recommend it now by clicking the button below.',
  no_result: 'No Results',
  back_search: 'Back to Search',
  please_wait: 'Loading...',

  ///////
  name: 'Name',
  f_name: 'First Name',
  l_name: 'Last Name',
  phone_number: 'Phone Number',
  email: 'Email',
  code: 'Code',
  password: 'Password',
  confirm_password: 'Confirm Password',
  current_password: 'Current Password',
  new_password: 'New Password',
  confirm_new_password: 'Confirm New Password',
  forgot_password: 'Forgot Password?',
  not_account: "Don't have an account? ",
  have_account: 'Already have an account? ',
  privacy_term: 'By submitting this, you accept the ',
  privacy_policy: 'Privacy Policy.',
  term: 'Terms of Services',

  ////////////
  hint_email_password_blank: 'Email and Password are required',
  hint_fName: 'Please Enter Your First Name',
  hint_lName: 'Please Enter Your Last Name',
  hint_email: 'Please Enter Email',
  hint_valid_email: 'Please Enter Valid Email ',
  hint_password: 'Please Enter Password',
  hint_code: 'Please Enter Code',
  hint_old_password: 'Please Enter Old Password',
  hint_valid_old_password: 'Old Password length must be between 6 to 20',
  hint_valid_password: 'Password length must be between 6 to 20',
  hint_in_valid_password: 'Please Enter Valid Password',
  hint_only_phone_number: 'Please Enter Only Number',
  hint_phone_number: 'Please Enter Phone Number',
  hint_dial_code: 'Please Select Dial Code',
  hint_category: 'Please Select Business Category',
  hint_business: 'Please Enter Business Name',
  hint_valid_business: 'Please Enter Valid Business Name',
  hint_valid_phone_number: 'Please Enter Valid Phone Number',
  hint_password_confirm: 'Password & Confirm Password did not match',
  hint_enter_password_confirm: 'Please Enter Confirm Password did not match',
  hint_name_blank_spaces: 'Name must not contain only blank spaces',
  hint_address_one: 'Please Enter Address1',
  hint_address_two: 'Please Enter Address2',
  hint_city: 'Please Enter City',
  hint_state: 'Please Select State',
  hint_zip_code: 'Please Enter Valid PostalCode',
  hint_zip: 'Please Enter PostalCode',
  hint_country: 'Please Select Country',
  hint_contact: `Allow ILoveBlackPeople to access your contacts.\n\nThis lets you invite friends & family to join the movement.`,
  // hint_contact: `We'd love you to share this application with friends & family. Can you allow ILoveBlackPeople to access your contacts?`,
  hint_location: `Allow ILoveBlackPeople to access this device's location.\n\nThis allows you to see nearby businesses and recommend Black friendly places.`,
  // hint_location: 'This allows you to see nearby businesses and recommend Black friendly places',
  // hint_location: `We'd want to get your current location. because I can give you information about the nearby business. Can you allow ILoveBlackPeople to access your current location?`,
  ///////////// Tabbar
  notification_tab: 'Notifications',
  business_tab: 'Business',
  home_tab: 'Home',
  close_tab: 'Close By',
  sync_tab: 'Sync Contacts',
  like: 'Like',
  skip: 'Skip',
  recmd_business: 'Recommend a Business',
  transportation: 'Transportation',
  business_info_title: 'Enter your Business Info',
  business_info_optional: 'Optional Business Info',
  business_name: 'Business Name',
  business_category: 'Business Category',
  business_email: 'Email Address',
  business_website: 'Website',
  business_location_title: 'Choose your Business Location',
  confirm_business_location_title: 'Confirm Your Business Location',
  search: 'Search',
  search_result: 'Search Result',
  address1: 'Address',
  address2: 'Address 2',
  address: 'Address',
  city: 'City',
  state: 'State',
  zip: 'Zip',
  country: 'Country',
  account: 'My Account',
  edit_profile: 'Edit Profile',
  change_ads: 'Change Address',
  change_pass: 'Change Password',
  about_us: 'About Us',
  choose_cat: 'Choose Category',
  clear_all: 'Clear All',
  apply: 'Apply',
  safe_city: 'Be safe in City',
  search_below: 'Search establishment below',
  where: 'Where...',
  what: 'What...',
  accommodation: 'Accommodation',
  beauty: 'Beauty',
  education: 'Education',
  finance: 'Finance',
  food: 'Food',
  health: 'Healthcare',
  legal: 'Legal',
  travel: 'Transportation',

  // Permission Alerts 
  Location_Permission_AlertHeading: 'Location Permissions',
  Location_Permission_AlertTextiOS: 'You have not access always location. go to settings and allow always location permissions',
  Location_Permission_AlertTextAndroid: 'You have not Access Location.Go to Settings and Allow Location Permissions',
  Motion_Permission_AlertHeading: 'Motion Permissions',
  Motion_Permission_AlertTextiOS: 'You have not Access motion. Go to settings under the Privacy section. Select the permission, then you can enable/disable that permission for appropriate apps',
};

const NUMBERS = {
  success: 200,
};
const MAP_KEY = 'AIzaSyDPVmDFjYvIe7Wow9NdBb-nm8x2FufG96M';

const CACHE_KEY = {
  access_token: 'ACCESS_TOKEN',
  refresh_token: 'REFRESH_TOKEN',
  token_type: 'TOKEN_TYPE',
  is_auth: 'IS_AUTH',
  user_data: 'USER_DATA',
};
//////////////////////////////////////
const API_URL = {
  start_ping: 'https://global-green-book-api-dev-kjjy8.ondigitalocean.app/ping',
  generate_token: 'oauth/token',
  refresh_token: 'oauth/refresh_token',
  signUp: 'user/create',
  login_email: 'auth/email',
  login_facebook: 'auth/facebook',
  login_google: 'auth/google',
  login_apple: 'auth/apple',
  forgot_password_start: 'auth/email/forgot_password/start',
  forgot_password_verify: 'auth/email/forgot_password/verify',
  get_user_detail: 'user/get',
  home: '',
  close: '',
  business_recommend: 'business/recommend',
  business_nearby: 'business/nearby',
  editProfile: 'user/update',
  // nearbyBusiness: 'https://global-green-book-api-dev-kjjy8.ondigitalocean.app/v1/business/nearby';
};
const WEB_URL = {
};


export { IMAGES, VIDEOS, STRINGS, NUMBERS, API_URL, CACHE_KEY, WEB_URL, MAP_KEY };
